### ISSUE TITLE
Possible file extracting error?

### ISSUE THREAD

**Issue by Varstahl** [mhvuze/WorldChunkTool#10]
I was playing around with your app today to go along [MaxDecorationLevel](https://www.nexusmods.com/monsterhunterworld/mods/545/), taking the `\common\text\steam\item_eng.gmd` and dropping it inside `nativePC\[…]`, but I noticed that several of the strings are completely blank. The description for the Cactuars endemic life is there, but their names are missing, just like all of Behemoth's material names (and probably a few more). Everything works correctly when I remove the `nativePC\common\text\steam\item_eng.gmd`. I noticed a lot of `Unavailable` inside the .gmd, but I read in #3 that this might be normal. Is what I'm experiencing a problem with the extraction, or is it there something I'm missing? Up to the first Kulve Taroth everything worked fine with just the `item_eng.gmd`.

Also, side note, release 1.1.2 still shows 1.1.1 from the command line.

**Comment by Varstahl** [comment]
Upon further investigation it seems that several strings are completely missing, although the placement is there, but they're just 0-length. Example:

> Tsuchinoko.\0
A creature that exists only in eye-\r\nwitness reports. To catch one is to\r\nbecome rich beyond imagination.\0
\0
\0
Gold Chip Fragment.

While the same file, extracted with another tool:

> Tsuchinoko.\0
A creature that exists only in eye-\r\nwitness reports. To catch one is to\r\nbecome rich beyond imagination.\0
Cactuar Cutting\0
A mysterious creature from Eorzea\0
Gold Chip Fragment.

This definitely looks like some bug. I'm not quite experienced with C#, but if you need help looking into it, let me know.

**Comment by mhvuze** [comment]
I just extracted chunk6 with the tool and opened the resulting `common\text\steam\item_eng.gmd`, looks fine to me? Are you sure you didn't accidentally extract an earlier chunk file? The instructions in the site you linked say to use chunk5 which of course contains outdated text files as of the Behemoth update and will not include the new strings.

![Image](https://i.imgur.com/bcF4LXz.png)

Thanks for the heads up about the version, fixed that in the code.

**Comment by Varstahl** [comment]
Huh! I've blindly followed the instructions, I guess that every chunk has different versions of the same file. I was extracting it from chunk5, that explains why (some of) the latest patch texts were missing. Thanks for the clarification.
