### ISSUE TITLE
unable to find oo2core_8win 64.dll

### ISSUE THREAD

**Issue by jaeminkim-yeet** [mhvuze/WorldChunkTool#14]
I tried to find oo2core8win64.dll from monster hunter world folder, but the file didnt existed anywhere and unable to find anywhere
![캡처](https://user-images.githubusercontent.com/60612446/73659810-eefeb300-46d1-11ea-8a62-7dafe4bfb548.PNG)

**Comment by mhvuze** [comment]
See readme:

> oo2core_8_win64.dll required. Monster Hunter World: Iceborne DOES NOT ship with this file. oo2core_5_win64.dll from the base game is outdated and won't work! You can find the new DLL in recent games like Warframe (F2P) and STAR WARS Jedi: Fallen Order. Simply search for it in the game installation directory and copy it to the same folder as the WorldChunkTool executable.
