### ISSUE TITLE
Pre-compiled Exe?

### ISSUE THREAD

**Issue by haldi4803** [mhvuze/WorldChunkTool#2]
having a Pre-compiled .exe to download would be too much trouble?

**Comment by Shadsterwolf** [comment]
Are you serious?

https://github.com/mhvuze/WorldChunkTool/releases

**Comment by haldi4803** [comment]
Sorry dude -.- my Fault. Didnt, check the Release version.
Downloaded visual studio and tried to compile it myself. Somehow failed horribly.
Then i found it on Nexus....
