### ISSUE TITLE
Some files only have "Invalid Message" in them

### ISSUE THREAD

**Issue by Fusion86** [mhvuze/WorldChunkTool#3]
For example all the `action_trial_(lang)` files (`chunk0\common\text`) in the languages `ara, kor, cht, pol, ptb, rus`.

Now I very much doubt that WorldChunkTool is the cause of this, maybe those strings just never appear in-game, or it falls back to the default language?

**Comment by mhvuze** [comment]
Yeah, "Invalid Message" is used for stuff that's not used in the game (yet). This is not an issue with the ChunkTool, the last questioned bit was solved with the current 1.1.
