### ISSUE TITLE
How?

### ISSUE THREAD

**Issue by TSelman61** [mhvuze/WorldChunkTool#9]
How do I use these files? I tried it with CMD but it didn't work
 In other words, can I export chunk0.bin?

**Comment by Varstahl** [comment]
The files you find in the main repository are only useful if you want to modify the code/compile it yourself. Otherwise you can grab one of the [releases](https://github.com/mhvuze/WorldChunkTool/releases), pre-compiled.

**Comment by TSelman61** [comment]
I'm sorry, the problem was with me. :-)
I forgot to copy the "oo2core_5_win64.dll" file.

 Thanks. :-)
